apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels: 
    group: {{ .Values.app.group }}
spec:
  type: {{ .Values.app.service.type }}
  selector:             
    app: {{ .Values.app.name }}
  ports:
  {{- range .Values.app.ports }}
  {{- if .servicePort }}
  - port: {{ .servicePort }}       
    targetPort: {{ .containerPort }} 
  {{- end }}
  {{- end }}