defaultBranch: master
dockerImagePrefix::default: stalchmst
subrepo::fibo::prefix: fibo
subrepo::fibo::url: https://github.com/state-alchemists/fibonacci-clock
link::myService/transport: shared-libs/python/transport
link::myService/database: shared-libs/python/database