environments:

  default:
    values:
    - commonImagePrefix: '{{ env "IMAGE_PREFIX" | default "local" }}'
    - commonImageTag: latest
    - host: localhost

  stable:
    values:
    - commonImagePrefix: '{{ env "IMAGE_PREFIX" | default "local" }}'
    - commonImageTag: v0.0.0
    - host: localhost

repositories:

- name: stable
  url: https://charts.helm.sh/stable/

releases:

- name: ingress-backend
  chart: stable/nginx-ingress
  version: 1.36.0

- name: ingress-controller
  chart: ./charts/ingress
  values:
  - ./values/ingress.yaml.gotmpl

- name: hello-world
  chart: ./charts/app
  values:
  - ./values/hello-world.yaml.gotmpl

- name: fibo
  chart: ./charts/app
  values:
  - ./values/fibo.yaml.gotmpl

- name: my-service
  chart: ./charts/app
  values:
  - ./values/my-service.yaml.gotmpl